# Generated by Django 6.0.2 on 2026-02-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogsapp', '0003_alter_blog_author_alter_blog_blog_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Draft', max_length=20),
        ),
    ]
